services:
  db:
    image: mysql:8.0
    container_name: mysql-proyecto-iglesia
    restart: always
    environment:
      # Ahora Docker lee directamente desde tu archivo .env
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: